//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 11:34:00 PM IST 
//


package in.gov.uidai.kyc.uid_kyc_request._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for raType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="raType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="FI"/&gt;
 *     &lt;enumeration value="FO"/&gt;
 *     &lt;enumeration value="IO"/&gt;
 *     &lt;enumeration value="FIO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "raType")
@XmlEnum
public enum RaType {

    F,
    I,
    O,
    FI,
    FO,
    IO,
    FIO;

    public String value() {
        return name();
    }

    public static RaType fromValue(String v) {
        return valueOf(v);
    }

}
