// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bfd.proto

package in.gov.uidai.bfdserver.protobuf;

public final class Bfd {
  private Bfd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code in.gov.uidai.bfdserver.protobuf.FingerPosition}
   */
  public enum FingerPosition
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEFT_INDEX = 1;</code>
     */
    LEFT_INDEX(1),
    /**
     * <code>LEFT_LITTLE = 2;</code>
     */
    LEFT_LITTLE(2),
    /**
     * <code>LEFT_MIDDLE = 3;</code>
     */
    LEFT_MIDDLE(3),
    /**
     * <code>LEFT_RING = 4;</code>
     */
    LEFT_RING(4),
    /**
     * <code>LEFT_THUMB = 5;</code>
     */
    LEFT_THUMB(5),
    /**
     * <code>RIGHT_INDEX = 6;</code>
     */
    RIGHT_INDEX(6),
    /**
     * <code>RIGHT_LITTLE = 7;</code>
     */
    RIGHT_LITTLE(7),
    /**
     * <code>RIGHT_MIDDLE = 8;</code>
     */
    RIGHT_MIDDLE(8),
    /**
     * <code>RIGHT_RING = 9;</code>
     */
    RIGHT_RING(9),
    /**
     * <code>RIGHT_THUMB = 10;</code>
     */
    RIGHT_THUMB(10),
    /**
     * <code>UNKNOWN = 11;</code>
     */
    UNKNOWN(11),
    ;

    /**
     * <code>LEFT_INDEX = 1;</code>
     */
    public static final int LEFT_INDEX_VALUE = 1;
    /**
     * <code>LEFT_LITTLE = 2;</code>
     */
    public static final int LEFT_LITTLE_VALUE = 2;
    /**
     * <code>LEFT_MIDDLE = 3;</code>
     */
    public static final int LEFT_MIDDLE_VALUE = 3;
    /**
     * <code>LEFT_RING = 4;</code>
     */
    public static final int LEFT_RING_VALUE = 4;
    /**
     * <code>LEFT_THUMB = 5;</code>
     */
    public static final int LEFT_THUMB_VALUE = 5;
    /**
     * <code>RIGHT_INDEX = 6;</code>
     */
    public static final int RIGHT_INDEX_VALUE = 6;
    /**
     * <code>RIGHT_LITTLE = 7;</code>
     */
    public static final int RIGHT_LITTLE_VALUE = 7;
    /**
     * <code>RIGHT_MIDDLE = 8;</code>
     */
    public static final int RIGHT_MIDDLE_VALUE = 8;
    /**
     * <code>RIGHT_RING = 9;</code>
     */
    public static final int RIGHT_RING_VALUE = 9;
    /**
     * <code>RIGHT_THUMB = 10;</code>
     */
    public static final int RIGHT_THUMB_VALUE = 10;
    /**
     * <code>UNKNOWN = 11;</code>
     */
    public static final int UNKNOWN_VALUE = 11;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FingerPosition valueOf(int value) {
      return forNumber(value);
    }

    public static FingerPosition forNumber(int value) {
      switch (value) {
        case 1: return LEFT_INDEX;
        case 2: return LEFT_LITTLE;
        case 3: return LEFT_MIDDLE;
        case 4: return LEFT_RING;
        case 5: return LEFT_THUMB;
        case 6: return RIGHT_INDEX;
        case 7: return RIGHT_LITTLE;
        case 8: return RIGHT_MIDDLE;
        case 9: return RIGHT_RING;
        case 10: return RIGHT_THUMB;
        case 11: return UNKNOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FingerPosition>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FingerPosition> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FingerPosition>() {
            public FingerPosition findValueByNumber(int number) {
              return FingerPosition.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.getDescriptor().getEnumTypes().get(0);
    }

    private static final FingerPosition[] VALUES = values();

    public static FingerPosition valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FingerPosition(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:in.gov.uidai.bfdserver.protobuf.FingerPosition)
  }

  public interface RbdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in.gov.uidai.bfdserver.protobuf.Rbd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ver = 1;</code>
     */
    boolean hasVer();
    /**
     * <code>required string ver = 1;</code>
     */
    java.lang.String getVer();
    /**
     * <code>required string ver = 1;</code>
     */
    com.google.protobuf.ByteString
        getVerBytes();

    /**
     * <code>required string ts = 2;</code>
     */
    boolean hasTs();
    /**
     * <code>required string ts = 2;</code>
     */
    java.lang.String getTs();
    /**
     * <code>required string ts = 2;</code>
     */
    com.google.protobuf.ByteString
        getTsBytes();

    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    boolean hasBios();
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getBios();
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder getBiosOrBuilder();
  }
  /**
   * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.Rbd}
   */
  public  static final class Rbd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in.gov.uidai.bfdserver.protobuf.Rbd)
      RbdOrBuilder {
    // Use Rbd.newBuilder() to construct.
    private Rbd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rbd() {
      ver_ = "";
      ts_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rbd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ver_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ts_ = bs;
              break;
            }
            case 34: {
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = bios_.toBuilder();
              }
              bios_ = input.readMessage(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bios_);
                bios_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.class, in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.Builder.class);
    }

    private int bitField0_;
    public static final int VER_FIELD_NUMBER = 1;
    private volatile java.lang.Object ver_;
    /**
     * <code>required string ver = 1;</code>
     */
    public boolean hasVer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ver = 1;</code>
     */
    public java.lang.String getVer() {
      java.lang.Object ref = ver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVerBytes() {
      java.lang.Object ref = ver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 2;
    private volatile java.lang.Object ts_;
    /**
     * <code>required string ts = 2;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ts = 2;</code>
     */
    public java.lang.String getTs() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ts_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ts = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTsBytes() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIOS_FIELD_NUMBER = 4;
    private in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios bios_;
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    public boolean hasBios() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getBios() {
      return bios_ == null ? in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance() : bios_;
    }
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
     */
    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder getBiosOrBuilder() {
      return bios_ == null ? in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance() : bios_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBios()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBios().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ver_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, getBios());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ver_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBios());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.gov.uidai.bfdserver.protobuf.Bfd.Rbd)) {
        return super.equals(obj);
      }
      in.gov.uidai.bfdserver.protobuf.Bfd.Rbd other = (in.gov.uidai.bfdserver.protobuf.Bfd.Rbd) obj;

      boolean result = true;
      result = result && (hasVer() == other.hasVer());
      if (hasVer()) {
        result = result && getVer()
            .equals(other.getVer());
      }
      result = result && (hasTs() == other.hasTs());
      if (hasTs()) {
        result = result && getTs()
            .equals(other.getTs());
      }
      result = result && (hasBios() == other.hasBios());
      if (hasBios()) {
        result = result && getBios()
            .equals(other.getBios());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVer()) {
        hash = (37 * hash) + VER_FIELD_NUMBER;
        hash = (53 * hash) + getVer().hashCode();
      }
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + getTs().hashCode();
      }
      if (hasBios()) {
        hash = (37 * hash) + BIOS_FIELD_NUMBER;
        hash = (53 * hash) + getBios().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.gov.uidai.bfdserver.protobuf.Bfd.Rbd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.Rbd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in.gov.uidai.bfdserver.protobuf.Rbd)
        in.gov.uidai.bfdserver.protobuf.Bfd.RbdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.class, in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.Builder.class);
      }

      // Construct using in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBiosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        ver_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (biosBuilder_ == null) {
          bios_ = null;
        } else {
          biosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.Rbd getDefaultInstanceForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.getDefaultInstance();
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.Rbd build() {
        in.gov.uidai.bfdserver.protobuf.Bfd.Rbd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.Rbd buildPartial() {
        in.gov.uidai.bfdserver.protobuf.Bfd.Rbd result = new in.gov.uidai.bfdserver.protobuf.Bfd.Rbd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ver_ = ver_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (biosBuilder_ == null) {
          result.bios_ = bios_;
        } else {
          result.bios_ = biosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.gov.uidai.bfdserver.protobuf.Bfd.Rbd) {
          return mergeFrom((in.gov.uidai.bfdserver.protobuf.Bfd.Rbd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.gov.uidai.bfdserver.protobuf.Bfd.Rbd other) {
        if (other == in.gov.uidai.bfdserver.protobuf.Bfd.Rbd.getDefaultInstance()) return this;
        if (other.hasVer()) {
          bitField0_ |= 0x00000001;
          ver_ = other.ver_;
          onChanged();
        }
        if (other.hasTs()) {
          bitField0_ |= 0x00000002;
          ts_ = other.ts_;
          onChanged();
        }
        if (other.hasBios()) {
          mergeBios(other.getBios());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVer()) {
          return false;
        }
        if (!hasTs()) {
          return false;
        }
        if (!hasBios()) {
          return false;
        }
        if (!getBios().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.gov.uidai.bfdserver.protobuf.Bfd.Rbd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.gov.uidai.bfdserver.protobuf.Bfd.Rbd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ver_ = "";
      /**
       * <code>required string ver = 1;</code>
       */
      public boolean hasVer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public java.lang.String getVer() {
        java.lang.Object ref = ver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVerBytes() {
        java.lang.Object ref = ver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder setVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder clearVer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ver_ = getDefaultInstance().getVer();
        onChanged();
        return this;
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder setVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ts_ = "";
      /**
       * <code>required string ts = 2;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ts = 2;</code>
       */
      public java.lang.String getTs() {
        java.lang.Object ref = ts_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ts_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ts = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        java.lang.Object ref = ts_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ts_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ts = 2;</code>
       */
      public Builder setTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ts = 2;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      /**
       * <code>required string ts = 2;</code>
       */
      public Builder setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }

      private in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios bios_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder> biosBuilder_;
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public boolean hasBios() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getBios() {
        if (biosBuilder_ == null) {
          return bios_ == null ? in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance() : bios_;
        } else {
          return biosBuilder_.getMessage();
        }
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public Builder setBios(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios value) {
        if (biosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bios_ = value;
          onChanged();
        } else {
          biosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public Builder setBios(
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder builderForValue) {
        if (biosBuilder_ == null) {
          bios_ = builderForValue.build();
          onChanged();
        } else {
          biosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public Builder mergeBios(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios value) {
        if (biosBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              bios_ != null &&
              bios_ != in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance()) {
            bios_ =
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.newBuilder(bios_).mergeFrom(value).buildPartial();
          } else {
            bios_ = value;
          }
          onChanged();
        } else {
          biosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public Builder clearBios() {
        if (biosBuilder_ == null) {
          bios_ = null;
          onChanged();
        } else {
          biosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder getBiosBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getBiosFieldBuilder().getBuilder();
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder getBiosOrBuilder() {
        if (biosBuilder_ != null) {
          return biosBuilder_.getMessageOrBuilder();
        } else {
          return bios_ == null ?
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance() : bios_;
        }
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.BfdBios bios = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder> 
          getBiosFieldBuilder() {
        if (biosBuilder_ == null) {
          biosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder>(
                  getBios(),
                  getParentForChildren(),
                  isClean());
          bios_ = null;
        }
        return biosBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in.gov.uidai.bfdserver.protobuf.Rbd)
    }

    // @@protoc_insertion_point(class_scope:in.gov.uidai.bfdserver.protobuf.Rbd)
    private static final in.gov.uidai.bfdserver.protobuf.Bfd.Rbd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.gov.uidai.bfdserver.protobuf.Bfd.Rbd();
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.Rbd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Rbd>
        PARSER = new com.google.protobuf.AbstractParser<Rbd>() {
      public Rbd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rbd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rbd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rbd> getParserForType() {
      return PARSER;
    }

    public in.gov.uidai.bfdserver.protobuf.Bfd.Rbd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BfdBiosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in.gov.uidai.bfdserver.protobuf.BfdBios)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> 
        getBioList();
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getBio(int index);
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    int getBioCount();
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    java.util.List<? extends in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder> 
        getBioOrBuilderList();
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder getBioOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.BfdBios}
   */
  public  static final class BfdBios extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in.gov.uidai.bfdserver.protobuf.BfdBios)
      BfdBiosOrBuilder {
    // Use BfdBios.newBuilder() to construct.
    private BfdBios(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BfdBios() {
      bio_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BfdBios(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                bio_ = new java.util.ArrayList<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio>();
                mutable_bitField0_ |= 0x00000001;
              }
              bio_.add(
                  input.readMessage(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          bio_ = java.util.Collections.unmodifiableList(bio_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.class, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder.class);
    }

    public static final int BIO_FIELD_NUMBER = 1;
    private java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> bio_;
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    public java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> getBioList() {
      return bio_;
    }
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    public java.util.List<? extends in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder> 
        getBioOrBuilderList() {
      return bio_;
    }
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    public int getBioCount() {
      return bio_.size();
    }
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getBio(int index) {
      return bio_.get(index);
    }
    /**
     * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
     */
    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder getBioOrBuilder(
        int index) {
      return bio_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getBioCount(); i++) {
        if (!getBio(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < bio_.size(); i++) {
        output.writeMessage(1, bio_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < bio_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bio_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios)) {
        return super.equals(obj);
      }
      in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios other = (in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios) obj;

      boolean result = true;
      result = result && getBioList()
          .equals(other.getBioList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBioCount() > 0) {
        hash = (37 * hash) + BIO_FIELD_NUMBER;
        hash = (53 * hash) + getBioList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.BfdBios}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in.gov.uidai.bfdserver.protobuf.BfdBios)
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBiosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.class, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.Builder.class);
      }

      // Construct using in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBioFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (bioBuilder_ == null) {
          bio_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bioBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getDefaultInstanceForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance();
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios build() {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios buildPartial() {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios result = new in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios(this);
        int from_bitField0_ = bitField0_;
        if (bioBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bio_ = java.util.Collections.unmodifiableList(bio_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bio_ = bio_;
        } else {
          result.bio_ = bioBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios) {
          return mergeFrom((in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios other) {
        if (other == in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios.getDefaultInstance()) return this;
        if (bioBuilder_ == null) {
          if (!other.bio_.isEmpty()) {
            if (bio_.isEmpty()) {
              bio_ = other.bio_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBioIsMutable();
              bio_.addAll(other.bio_);
            }
            onChanged();
          }
        } else {
          if (!other.bio_.isEmpty()) {
            if (bioBuilder_.isEmpty()) {
              bioBuilder_.dispose();
              bioBuilder_ = null;
              bio_ = other.bio_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bioBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBioFieldBuilder() : null;
            } else {
              bioBuilder_.addAllMessages(other.bio_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getBioCount(); i++) {
          if (!getBio(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> bio_ =
        java.util.Collections.emptyList();
      private void ensureBioIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bio_ = new java.util.ArrayList<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio>(bio_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder> bioBuilder_;

      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> getBioList() {
        if (bioBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bio_);
        } else {
          return bioBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public int getBioCount() {
        if (bioBuilder_ == null) {
          return bio_.size();
        } else {
          return bioBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getBio(int index) {
        if (bioBuilder_ == null) {
          return bio_.get(index);
        } else {
          return bioBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder setBio(
          int index, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio value) {
        if (bioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBioIsMutable();
          bio_.set(index, value);
          onChanged();
        } else {
          bioBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder setBio(
          int index, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder builderForValue) {
        if (bioBuilder_ == null) {
          ensureBioIsMutable();
          bio_.set(index, builderForValue.build());
          onChanged();
        } else {
          bioBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder addBio(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio value) {
        if (bioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBioIsMutable();
          bio_.add(value);
          onChanged();
        } else {
          bioBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder addBio(
          int index, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio value) {
        if (bioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBioIsMutable();
          bio_.add(index, value);
          onChanged();
        } else {
          bioBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder addBio(
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder builderForValue) {
        if (bioBuilder_ == null) {
          ensureBioIsMutable();
          bio_.add(builderForValue.build());
          onChanged();
        } else {
          bioBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder addBio(
          int index, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder builderForValue) {
        if (bioBuilder_ == null) {
          ensureBioIsMutable();
          bio_.add(index, builderForValue.build());
          onChanged();
        } else {
          bioBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder addAllBio(
          java.lang.Iterable<? extends in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio> values) {
        if (bioBuilder_ == null) {
          ensureBioIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bio_);
          onChanged();
        } else {
          bioBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder clearBio() {
        if (bioBuilder_ == null) {
          bio_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bioBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public Builder removeBio(int index) {
        if (bioBuilder_ == null) {
          ensureBioIsMutable();
          bio_.remove(index);
          onChanged();
        } else {
          bioBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder getBioBuilder(
          int index) {
        return getBioFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder getBioOrBuilder(
          int index) {
        if (bioBuilder_ == null) {
          return bio_.get(index);  } else {
          return bioBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public java.util.List<? extends in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder> 
           getBioOrBuilderList() {
        if (bioBuilder_ != null) {
          return bioBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bio_);
        }
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder addBioBuilder() {
        return getBioFieldBuilder().addBuilder(
            in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.getDefaultInstance());
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder addBioBuilder(
          int index) {
        return getBioFieldBuilder().addBuilder(
            index, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.getDefaultInstance());
      }
      /**
       * <code>repeated .in.gov.uidai.bfdserver.protobuf.BfdBio bio = 1;</code>
       */
      public java.util.List<in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder> 
           getBioBuilderList() {
        return getBioFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder> 
          getBioFieldBuilder() {
        if (bioBuilder_ == null) {
          bioBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder>(
                  bio_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bio_ = null;
        }
        return bioBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in.gov.uidai.bfdserver.protobuf.BfdBios)
    }

    // @@protoc_insertion_point(class_scope:in.gov.uidai.bfdserver.protobuf.BfdBios)
    private static final in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios();
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BfdBios>
        PARSER = new com.google.protobuf.AbstractParser<BfdBios>() {
      public BfdBios parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BfdBios(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BfdBios> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BfdBios> getParserForType() {
      return PARSER;
    }

    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBios getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BfdBioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in.gov.uidai.bfdserver.protobuf.BfdBio)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 nfiq = 1;</code>
     */
    boolean hasNfiq();
    /**
     * <code>required int32 nfiq = 1;</code>
     */
    int getNfiq();

    /**
     * <code>required int32 na = 2;</code>
     */
    boolean hasNa();
    /**
     * <code>required int32 na = 2;</code>
     */
    int getNa();

    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
     */
    boolean hasPos();
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
     */
    in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition getPos();

    /**
     * <code>required bytes content = 4;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.BfdBio}
   */
  public  static final class BfdBio extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in.gov.uidai.bfdserver.protobuf.BfdBio)
      BfdBioOrBuilder {
    // Use BfdBio.newBuilder() to construct.
    private BfdBio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BfdBio() {
      nfiq_ = 0;
      na_ = 0;
      pos_ = 1;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BfdBio(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nfiq_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              na_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition value = in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                pos_ = rawValue;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.class, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder.class);
    }

    private int bitField0_;
    public static final int NFIQ_FIELD_NUMBER = 1;
    private int nfiq_;
    /**
     * <code>required int32 nfiq = 1;</code>
     */
    public boolean hasNfiq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 nfiq = 1;</code>
     */
    public int getNfiq() {
      return nfiq_;
    }

    public static final int NA_FIELD_NUMBER = 2;
    private int na_;
    /**
     * <code>required int32 na = 2;</code>
     */
    public boolean hasNa() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 na = 2;</code>
     */
    public int getNa() {
      return na_;
    }

    public static final int POS_FIELD_NUMBER = 3;
    private int pos_;
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
     */
    public boolean hasPos() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
     */
    public in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition getPos() {
      in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition result = in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition.valueOf(pos_);
      return result == null ? in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition.LEFT_INDEX : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNfiq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNa()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, nfiq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, na_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, pos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nfiq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, na_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, pos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio)) {
        return super.equals(obj);
      }
      in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio other = (in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio) obj;

      boolean result = true;
      result = result && (hasNfiq() == other.hasNfiq());
      if (hasNfiq()) {
        result = result && (getNfiq()
            == other.getNfiq());
      }
      result = result && (hasNa() == other.hasNa());
      if (hasNa()) {
        result = result && (getNa()
            == other.getNa());
      }
      result = result && (hasPos() == other.hasPos());
      if (hasPos()) {
        result = result && pos_ == other.pos_;
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNfiq()) {
        hash = (37 * hash) + NFIQ_FIELD_NUMBER;
        hash = (53 * hash) + getNfiq();
      }
      if (hasNa()) {
        hash = (37 * hash) + NA_FIELD_NUMBER;
        hash = (53 * hash) + getNa();
      }
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + pos_;
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in.gov.uidai.bfdserver.protobuf.BfdBio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in.gov.uidai.bfdserver.protobuf.BfdBio)
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.class, in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.Builder.class);
      }

      // Construct using in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nfiq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        na_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pos_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getDefaultInstanceForType() {
        return in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.getDefaultInstance();
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio build() {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio buildPartial() {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio result = new in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nfiq_ = nfiq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.na_ = na_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pos_ = pos_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio) {
          return mergeFrom((in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio other) {
        if (other == in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio.getDefaultInstance()) return this;
        if (other.hasNfiq()) {
          setNfiq(other.getNfiq());
        }
        if (other.hasNa()) {
          setNa(other.getNa());
        }
        if (other.hasPos()) {
          setPos(other.getPos());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNfiq()) {
          return false;
        }
        if (!hasNa()) {
          return false;
        }
        if (!hasPos()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int nfiq_ ;
      /**
       * <code>required int32 nfiq = 1;</code>
       */
      public boolean hasNfiq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 nfiq = 1;</code>
       */
      public int getNfiq() {
        return nfiq_;
      }
      /**
       * <code>required int32 nfiq = 1;</code>
       */
      public Builder setNfiq(int value) {
        bitField0_ |= 0x00000001;
        nfiq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nfiq = 1;</code>
       */
      public Builder clearNfiq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nfiq_ = 0;
        onChanged();
        return this;
      }

      private int na_ ;
      /**
       * <code>required int32 na = 2;</code>
       */
      public boolean hasNa() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 na = 2;</code>
       */
      public int getNa() {
        return na_;
      }
      /**
       * <code>required int32 na = 2;</code>
       */
      public Builder setNa(int value) {
        bitField0_ |= 0x00000002;
        na_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 na = 2;</code>
       */
      public Builder clearNa() {
        bitField0_ = (bitField0_ & ~0x00000002);
        na_ = 0;
        onChanged();
        return this;
      }

      private int pos_ = 1;
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
       */
      public in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition getPos() {
        in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition result = in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition.valueOf(pos_);
        return result == null ? in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition.LEFT_INDEX : result;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
       */
      public Builder setPos(in.gov.uidai.bfdserver.protobuf.Bfd.FingerPosition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        pos_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .in.gov.uidai.bfdserver.protobuf.FingerPosition pos = 3;</code>
       */
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pos_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in.gov.uidai.bfdserver.protobuf.BfdBio)
    }

    // @@protoc_insertion_point(class_scope:in.gov.uidai.bfdserver.protobuf.BfdBio)
    private static final in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio();
    }

    public static in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BfdBio>
        PARSER = new com.google.protobuf.AbstractParser<BfdBio>() {
      public BfdBio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BfdBio(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BfdBio> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BfdBio> getParserForType() {
      return PARSER;
    }

    public in.gov.uidai.bfdserver.protobuf.Bfd.BfdBio getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbfd.proto\022\037in.gov.uidai.bfdserver.prot" +
      "obuf\"V\n\003Rbd\022\013\n\003ver\030\001 \002(\t\022\n\n\002ts\030\002 \002(\t\0226\n\004" +
      "bios\030\004 \002(\0132(.in.gov.uidai.bfdserver.prot" +
      "obuf.BfdBios\"?\n\007BfdBios\0224\n\003bio\030\001 \003(\0132\'.i" +
      "n.gov.uidai.bfdserver.protobuf.BfdBio\"q\n" +
      "\006BfdBio\022\014\n\004nfiq\030\001 \002(\005\022\n\n\002na\030\002 \002(\005\022<\n\003pos" +
      "\030\003 \002(\0162/.in.gov.uidai.bfdserver.protobuf" +
      ".FingerPosition\022\017\n\007content\030\004 \002(\014*\304\001\n\016Fin" +
      "gerPosition\022\016\n\nLEFT_INDEX\020\001\022\017\n\013LEFT_LITT" +
      "LE\020\002\022\017\n\013LEFT_MIDDLE\020\003\022\r\n\tLEFT_RING\020\004\022\016\n\n",
      "LEFT_THUMB\020\005\022\017\n\013RIGHT_INDEX\020\006\022\020\n\014RIGHT_L" +
      "ITTLE\020\007\022\020\n\014RIGHT_MIDDLE\020\010\022\016\n\nRIGHT_RING\020" +
      "\t\022\017\n\013RIGHT_THUMB\020\n\022\013\n\007UNKNOWN\020\013"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_gov_uidai_bfdserver_protobuf_Rbd_descriptor,
        new java.lang.String[] { "Ver", "Ts", "Bios", });
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_gov_uidai_bfdserver_protobuf_BfdBios_descriptor,
        new java.lang.String[] { "Bio", });
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_gov_uidai_bfdserver_protobuf_BfdBio_descriptor,
        new java.lang.String[] { "Nfiq", "Na", "Pos", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
